# BUILD STAGE
FROM node:16-alpine AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn build
RUN yarn --prod

# PRODUCTION STAGE
FROM node:16-alpine AS prod
WORKDIR /app
COPY --from=build /app/build ./build/
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules ./node_modules/
ENTRYPOINT ["yarn", "start:prod"]
