# BUILD STAGE
FROM node:16-alpine AS build
WORKDIR /app
COPY package*.json ./
ENV NODE_ENV=production
RUN yarn
COPY . .
RUN yarn build
RUN npm prune --production

# PRODUCTION STAGE
FROM node:16-alpine AS prod
WORKDIR /app
COPY --from=build /app/build ./build/
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules ./node_modules/
ENTRYPOINT ["yarn", "start:prod"]
